# Generated by Django 3.2.6 on 2021-08-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_nowplaying_upcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='films.Actor'),
        ),
    ]
