# Generated by Django 3.2.6 on 2021-08-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20210813_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=1023),
        ),
    ]
