# Generated by Django 3.2.6 on 2021-08-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20210813_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123123, max_length=255),
            preserve_default=False,
        ),
    ]
